# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      htcondor:
        image: htcondor/mini:el7
        env:
          _CONDOR_BIND_ALL_INTERFACES: "true"
          _CONDOR_SEC_DEFAULT_AUTHENTICATION_METHODS: "CLAIMTOBE"
          _CONDOR_SEC_CLIENT_AUTHENTICATION_METHODS: "$(SEC_DEFAULT_AUTHENTICATION_METHODS)"
        ports:
        - 9618:9618
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install HTCondor
      run: |
        curl -fsSL https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-current-Key | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] https://research.cs.wisc.edu/htcondor/repo/ubuntu/current focal main\ndeb-src https://research.cs.wisc.edu/htcondor/repo/ubuntu/current focal main" > /etc/apt/sources.list.d/htcondor.list'
        sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y htcondor
    - name: Install dependencies
      id: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 pyglidein_server --count --show-source --statistics
    - name: Test and Coverage
      if: always() && steps.dependencies.outcome != 'failure'
      run: |
        coverage run -m pytest tests --log-level=INFO
    - name: Coverage Text Report
      if: always() && steps.dependencies.outcome != 'failure'
      run: |
        coverage report -m --fail-under=50
